---
- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: unarchive backend
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i        

- name: "Execute app using PM2"
  shell: |    
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "start PM2 as service"
  become: true
  shell: |      
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu -hp /home/ubuntu